<?xml version="1.0" encoding="utf-8"?><Database Name="handHeldDB" Class="transDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=kpsprd;Initial Catalog=handHeldDB;User ID=sa" SettingsObjectName="keyencePartsVerifier.Properties.Settings" SettingsPropertyName="handHeldDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_sys_config" Member="tbl_sys_configs">
    <Type Name="tbl_sys_config">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="model" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="sPeriod" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="remarks" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="dateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="dateFinished" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="PhysicalModel" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Lot_or_Ref" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Physical_Type" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_users_rights" Member="tbl_users_rights">
    <Type Name="tbl_users_right">
      <Column Name="userNo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userName" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IDNo" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="firstName" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="lastName" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="deptID" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="emailAddress" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="accessRights" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="version" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_web2_maintenance" Member="tbl_web2_maintenances">
    <Type Name="tbl_web2_maintenance">
      <Column Name="mnt_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="order_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lineName" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="machineName" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="tableName" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="modelName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="feederLocation" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="partsName" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="dateUpdated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="updatedByUser" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_web2_employee" Member="tbl_web2_employees">
    <Type Name="tbl_web2_employee">
      <Column Name="emp_id" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="emp_name" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_web2_uploadedText" Member="tbl_web2_uploadedTexts">
    <Type Name="tbl_web2_uploadedText">
      <Column Name="uploadID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="uploadTitle" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="uploadBody" Type="System.String" DbType="Char(2050)" CanBeNull="true" />
      <Column Name="uploadDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_web2_transaction" Member="tbl_web2_transactions">
    <Type Name="tbl_web2_transaction">
      <Column Name="transID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="lineName" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="machineName" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="tableName" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="modelName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="feederLocation" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="partsName" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="inspector" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="remarks" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="dt_trans" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="period" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="makerCode" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="makerName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="lotNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="vendorCode" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="vendorName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="datePrinted" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="invoiceNo" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="repacking" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="invoiceQty" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TransactionDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateTimeNow" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateTimeNext" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_web2_maintenance_history" Member="tbl_web2_maintenance_histories">
    <Type Name="tbl_web2_maintenance_history">
      <Column Name="transfer_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="mnt_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="order_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lineName" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="machineName" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="tableName" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="modelName" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="feederLocation" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="partsName" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="dateUpdated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="updatedByUser" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="dateTransfer" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_InActiveModels" Member="tbl_InActiveModels">
    <Type Name="tbl_InActiveModel">
      <Column Name="modelName" Type="System.String" DbType="VarChar(500) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.dbPBCoreSolution_tbl_RT1SMTPickingList" Member="dbPBCoreSolution_tbl_RT1SMTPickingLists">
    <Type Name="dbPBCoreSolution_tbl_RT1SMTPickingList">
      <Column Name="SPL_Index" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SPL_LON_Index" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SPL_CustomerNo" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="SPL_ModelNo" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="SPL_Rinks_PO_No" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="SPL_PO_Qty" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SPL_Qty" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SPL_LotNo" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SPL_Destination" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="SPL_ModeofShipment" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="SPL_ShippingSchedule" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="SPL_WarehouseIncharge" Type="System.String" DbType="VarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="SPL_Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Action" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="UserLog" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateModified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.dbPBCoreSolution_tbl_REX_SMTPickingList" Member="dbPBCoreSolution_tbl_REX_SMTPickingLists">
    <Type Name="dbPBCoreSolution_tbl_REX_SMTPickingList">
      <Column Name="SPL_Index" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="SPL_LON_Index" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SPL_Series" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="SPL_ModelNo" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="SPL_Rinks_PO_No" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="SPL_PO_Qty" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SPL_Qty" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SPL_LotNo" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SPL_Destination" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="SPL_ModeofShipment" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="SPL_ShippingSchedule" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="SPL_WarehouseIncharge" Type="System.String" DbType="VarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="SPL_Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Action" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="UserLog" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateModified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.view_get_prodLotNo2" Member="view_get_prodLotNo2s">
    <Type Name="view_get_prodLotNo2">
      <Column Name="SPL_LotNo" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="modelName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SPL_Series" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="transID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.view_get_prodLotNo3" Member="view_get_prodLotNo3s">
    <Type Name="view_get_prodLotNo3">
      <Column Name="SPL_LotNo" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="modelName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SPL_Series" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="transID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.view_get_prodLotNo4" Member="view_get_prodLotNo4s">
    <Type Name="view_get_prodLotNo4">
      <Column Name="modelName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SPL_ModelNo" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="SPL_LotNo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.view_get_prodLotNo5" Member="view_get_prodLotNo5s">
    <Type Name="view_get_prodLotNo5">
      <Column Name="SPL_ModelNo" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="SPL_LotNo" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SPL_Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SPL_Series" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="CGITCH" Type="System.String" DbType="Char(12)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_getModelName" Method="sp_getModelName">
    <ElementType Name="sp_getModelNameResult">
      <Column Name="modelName" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_get_web2_maintenance" Method="sp_get_web2_maintenance">
    <ElementType Name="sp_get_web2_maintenanceResult">
      <Column Name="mnt_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="order_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lineName" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="machineName" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="tableName" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="modelName" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="feederLocation" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="partsName" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="dateUpdated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="updatedByUser" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.prodLotNo" Method="prodLotNo">
    <Parameter Name="SPL_ModelNo" Parameter="sPL_ModelNo" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="SPL_Series" Parameter="sPL_Series" Type="System.String" DbType="NVarChar(100)" />
    <ElementType Name="prodLotNoResult">
      <Column Name="SPL_LotNo" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>