#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace keyencePartsVerifier.MODELS
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbPBCoreSolution")]
	public partial class trans2DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_REX_SMTPickingList(tbl_REX_SMTPickingList instance);
    partial void Updatetbl_REX_SMTPickingList(tbl_REX_SMTPickingList instance);
    partial void Deletetbl_REX_SMTPickingList(tbl_REX_SMTPickingList instance);
    #endregion
		
		public trans2DataContext() : 
				base(global::keyencePartsVerifier.Properties.Settings.Default.dbPBCoreSolutionConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public trans2DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public trans2DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public trans2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public trans2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_REX_SMTPickingList> tbl_REX_SMTPickingLists
		{
			get
			{
				return this.GetTable<tbl_REX_SMTPickingList>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_REX_SMTPickingList")]
	public partial class tbl_REX_SMTPickingList : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _SPL_Index;
		
		private System.Nullable<int> _SPL_LON_Index;
		
		private string _SPL_Series;
		
		private string _SPL_ModelNo;
		
		private string _SPL_Rinks_PO_No;
		
		private int _SPL_PO_Qty;
		
		private System.Nullable<int> _SPL_Qty;
		
		private string _SPL_LotNo;
		
		private string _SPL_Destination;
		
		private string _SPL_ModeofShipment;
		
		private System.DateTime _SPL_ShippingSchedule;
		
		private string _SPL_WarehouseIncharge;
		
		private string _SPL_Status;
		
		private string _Action;
		
		private string _UserLog;
		
		private System.Nullable<System.DateTime> _DateCreated;
		
		private System.Nullable<System.DateTime> _DateModified;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSPL_IndexChanging(long value);
    partial void OnSPL_IndexChanged();
    partial void OnSPL_LON_IndexChanging(System.Nullable<int> value);
    partial void OnSPL_LON_IndexChanged();
    partial void OnSPL_SeriesChanging(string value);
    partial void OnSPL_SeriesChanged();
    partial void OnSPL_ModelNoChanging(string value);
    partial void OnSPL_ModelNoChanged();
    partial void OnSPL_Rinks_PO_NoChanging(string value);
    partial void OnSPL_Rinks_PO_NoChanged();
    partial void OnSPL_PO_QtyChanging(int value);
    partial void OnSPL_PO_QtyChanged();
    partial void OnSPL_QtyChanging(System.Nullable<int> value);
    partial void OnSPL_QtyChanged();
    partial void OnSPL_LotNoChanging(string value);
    partial void OnSPL_LotNoChanged();
    partial void OnSPL_DestinationChanging(string value);
    partial void OnSPL_DestinationChanged();
    partial void OnSPL_ModeofShipmentChanging(string value);
    partial void OnSPL_ModeofShipmentChanged();
    partial void OnSPL_ShippingScheduleChanging(System.DateTime value);
    partial void OnSPL_ShippingScheduleChanged();
    partial void OnSPL_WarehouseInchargeChanging(string value);
    partial void OnSPL_WarehouseInchargeChanged();
    partial void OnSPL_StatusChanging(string value);
    partial void OnSPL_StatusChanged();
    partial void OnActionChanging(string value);
    partial void OnActionChanged();
    partial void OnUserLogChanging(string value);
    partial void OnUserLogChanged();
    partial void OnDateCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateCreatedChanged();
    partial void OnDateModifiedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateModifiedChanged();
    #endregion
		
		public tbl_REX_SMTPickingList()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPL_Index", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long SPL_Index
		{
			get
			{
				return this._SPL_Index;
			}
			set
			{
				if ((this._SPL_Index != value))
				{
					this.OnSPL_IndexChanging(value);
					this.SendPropertyChanging();
					this._SPL_Index = value;
					this.SendPropertyChanged("SPL_Index");
					this.OnSPL_IndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPL_LON_Index", DbType="Int")]
		public System.Nullable<int> SPL_LON_Index
		{
			get
			{
				return this._SPL_LON_Index;
			}
			set
			{
				if ((this._SPL_LON_Index != value))
				{
					this.OnSPL_LON_IndexChanging(value);
					this.SendPropertyChanging();
					this._SPL_LON_Index = value;
					this.SendPropertyChanged("SPL_LON_Index");
					this.OnSPL_LON_IndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPL_Series", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string SPL_Series
		{
			get
			{
				return this._SPL_Series;
			}
			set
			{
				if ((this._SPL_Series != value))
				{
					this.OnSPL_SeriesChanging(value);
					this.SendPropertyChanging();
					this._SPL_Series = value;
					this.SendPropertyChanged("SPL_Series");
					this.OnSPL_SeriesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPL_ModelNo", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string SPL_ModelNo
		{
			get
			{
				return this._SPL_ModelNo;
			}
			set
			{
				if ((this._SPL_ModelNo != value))
				{
					this.OnSPL_ModelNoChanging(value);
					this.SendPropertyChanging();
					this._SPL_ModelNo = value;
					this.SendPropertyChanged("SPL_ModelNo");
					this.OnSPL_ModelNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPL_Rinks_PO_No", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string SPL_Rinks_PO_No
		{
			get
			{
				return this._SPL_Rinks_PO_No;
			}
			set
			{
				if ((this._SPL_Rinks_PO_No != value))
				{
					this.OnSPL_Rinks_PO_NoChanging(value);
					this.SendPropertyChanging();
					this._SPL_Rinks_PO_No = value;
					this.SendPropertyChanged("SPL_Rinks_PO_No");
					this.OnSPL_Rinks_PO_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPL_PO_Qty", DbType="Int NOT NULL")]
		public int SPL_PO_Qty
		{
			get
			{
				return this._SPL_PO_Qty;
			}
			set
			{
				if ((this._SPL_PO_Qty != value))
				{
					this.OnSPL_PO_QtyChanging(value);
					this.SendPropertyChanging();
					this._SPL_PO_Qty = value;
					this.SendPropertyChanged("SPL_PO_Qty");
					this.OnSPL_PO_QtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPL_Qty", DbType="Int")]
		public System.Nullable<int> SPL_Qty
		{
			get
			{
				return this._SPL_Qty;
			}
			set
			{
				if ((this._SPL_Qty != value))
				{
					this.OnSPL_QtyChanging(value);
					this.SendPropertyChanging();
					this._SPL_Qty = value;
					this.SendPropertyChanged("SPL_Qty");
					this.OnSPL_QtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPL_LotNo", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string SPL_LotNo
		{
			get
			{
				return this._SPL_LotNo;
			}
			set
			{
				if ((this._SPL_LotNo != value))
				{
					this.OnSPL_LotNoChanging(value);
					this.SendPropertyChanging();
					this._SPL_LotNo = value;
					this.SendPropertyChanged("SPL_LotNo");
					this.OnSPL_LotNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPL_Destination", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string SPL_Destination
		{
			get
			{
				return this._SPL_Destination;
			}
			set
			{
				if ((this._SPL_Destination != value))
				{
					this.OnSPL_DestinationChanging(value);
					this.SendPropertyChanging();
					this._SPL_Destination = value;
					this.SendPropertyChanged("SPL_Destination");
					this.OnSPL_DestinationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPL_ModeofShipment", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string SPL_ModeofShipment
		{
			get
			{
				return this._SPL_ModeofShipment;
			}
			set
			{
				if ((this._SPL_ModeofShipment != value))
				{
					this.OnSPL_ModeofShipmentChanging(value);
					this.SendPropertyChanging();
					this._SPL_ModeofShipment = value;
					this.SendPropertyChanged("SPL_ModeofShipment");
					this.OnSPL_ModeofShipmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPL_ShippingSchedule", DbType="Date NOT NULL")]
		public System.DateTime SPL_ShippingSchedule
		{
			get
			{
				return this._SPL_ShippingSchedule;
			}
			set
			{
				if ((this._SPL_ShippingSchedule != value))
				{
					this.OnSPL_ShippingScheduleChanging(value);
					this.SendPropertyChanging();
					this._SPL_ShippingSchedule = value;
					this.SendPropertyChanged("SPL_ShippingSchedule");
					this.OnSPL_ShippingScheduleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPL_WarehouseIncharge", DbType="VarChar(2000) NOT NULL", CanBeNull=false)]
		public string SPL_WarehouseIncharge
		{
			get
			{
				return this._SPL_WarehouseIncharge;
			}
			set
			{
				if ((this._SPL_WarehouseIncharge != value))
				{
					this.OnSPL_WarehouseInchargeChanging(value);
					this.SendPropertyChanging();
					this._SPL_WarehouseIncharge = value;
					this.SendPropertyChanged("SPL_WarehouseIncharge");
					this.OnSPL_WarehouseInchargeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPL_Status", DbType="VarChar(50)")]
		public string SPL_Status
		{
			get
			{
				return this._SPL_Status;
			}
			set
			{
				if ((this._SPL_Status != value))
				{
					this.OnSPL_StatusChanging(value);
					this.SendPropertyChanging();
					this._SPL_Status = value;
					this.SendPropertyChanged("SPL_Status");
					this.OnSPL_StatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Action", DbType="VarChar(200)")]
		public string Action
		{
			get
			{
				return this._Action;
			}
			set
			{
				if ((this._Action != value))
				{
					this.OnActionChanging(value);
					this.SendPropertyChanging();
					this._Action = value;
					this.SendPropertyChanged("Action");
					this.OnActionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserLog", DbType="VarChar(200)")]
		public string UserLog
		{
			get
			{
				return this._UserLog;
			}
			set
			{
				if ((this._UserLog != value))
				{
					this.OnUserLogChanging(value);
					this.SendPropertyChanging();
					this._UserLog = value;
					this.SendPropertyChanged("UserLog");
					this.OnUserLogChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateModified", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateModified
		{
			get
			{
				return this._DateModified;
			}
			set
			{
				if ((this._DateModified != value))
				{
					this.OnDateModifiedChanging(value);
					this.SendPropertyChanging();
					this._DateModified = value;
					this.SendPropertyChanged("DateModified");
					this.OnDateModifiedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
